version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: educhain_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=EduChain@2024!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - educhain-network

  blockchain:
    image: ${DOCKER_USERNAME:-tuankhue}/educhain-blockchain:latest
    build:
      context: ./smartContract
      dockerfile: Dockerfile
    container_name: educhain_blockchain
    ports:
      - "8545:8545"
    networks:
      - educhain-network

  backend:
    image: ${DOCKER_USERNAME:-tuankhue}/educhain-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: educhain_api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SchoolDB;User Id=sa;Password=EduChain@2024!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
      - Blockchain__RpcUrl=http://blockchain:8545
    depends_on:
      - sqlserver
      - blockchain
    networks:
      - educhain-network

  frontend:
    image: ${DOCKER_USERNAME:-tuankhue}/educhain-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: educhain_web
    depends_on:
      - backend
    ports:
      - "3001:3000"
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8080/api
    networks:
      - educhain-network

volumes:
  sql_data:


networks:
  educhain-network:
    driver: bridge
